#!D:\Perkuliahan\Semester 5\Poyek Sains Data\PSD\venv_py3.11\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
